#!/usr/bin/env bash
#Displays the contents of file `/etc/passwd`.
#only displays the username, user id, and user home directory path for the user.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
