#!/usr/bin/env bash
#displays numbers from 1 to 20 and:

#displays 4 and then bad luck from china for the 4th loop iteration 
#displays 9 and then bad luck from japan for the 9th loop iteration 
#displays 17 and then bad luck from italy for the 17th loop iteration 

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in 
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ )) 
done
