#!/usr/bin/env bash
#a script that stops  a process of '6-stop_me_if_you_can' without using kill or killall command

# Check if the "4-to_infinity_and_beyond" process is running
if pgrep -x "4-to_infinity_and_beyond" > /dev/null; then
  # Terminate the process by sending a termination signal
  pkill -x "4-to_infinity_and_beyond"
  echo "Process stopped successfully."
else
  echo "Process not found."
fi
